name: Build PowerSwitcher.TrayApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore PowerSwitcher.TrayApp/PowerSwitcher.TrayApp.csproj

      - name: Build and publish
        run: dotnet publish PowerSwitcher.TrayApp/PowerSwitcher.TrayApp.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerSwitcher-TrayApp
          path: output/
