name: Build PowerSwitcher TrayApp

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core SDK 9.0.303
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.303

    - name: Install .NET Framework 4.5 Targeting Pack
      run: |
        Invoke-WebRequest -Uri "https://download.microsoft.com/download/7/B/6/7B64C3A1-C9BA-4B1D-B3C2-5C2654E8FA7C/NDP45-DevPack-KB2872776-ENU.exe" -OutFile "ndp45.exe"
        Start-Process .\ndp45.exe -ArgumentList "/quiet" -Wait

    - name: Publish PowerSwitcher.TrayApp
      run: |
        dotnet publish PowerSwitcher.TrayApp/PowerSwitcher.TrayApp.csproj `
          -c Release `
          -r win-x64 `
          -p:PublishSingleFile=true `
          -p:SelfContained=true `
          -p:IncludeAllContentForSelfExtract=true `
          -o output

    - name: Show output files
      run: dir /s output

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PowerSwitcher-TrayApp
        path: output/*.exe
