name: Build PowerSwitcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish PowerSwitcher
        run: >
          dotnet publish PowerSwitcher/PowerSwitcher.csproj
          -c Release -r win-x64
          -p:PublishSingleFile=true
          -p:SelfContained=true
          -p:IncludeAllContentForSelfExtract=true
        shell: cmd

      - name: Find and list all EXE files
        run: dir /s /b PowerSwitcher\bin\Release\*.exe
        shell: cmd

      - name: Archive final PowerSwitcher.exe
        run: powershell Compress-Archive -Path PowerSwitcher\bin\Release\**\PowerSwitcher.exe -DestinationPath PowerSwitcher.zip
        shell: pwsh

      - name: Upload artifact ZIP
        uses: actions/upload-artifact@v4
        with:
          name: PowerSwitcher
          path: PowerSwitcher.zip
