name: Build PowerSwitcher.TrayApp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Tray App
        run: >
          dotnet publish PowerSwitcher.TrayApp/PowerSwitcher.TrayApp.csproj
          -c Release -r win-x64
          -p:PublishSingleFile=true
          -p:SelfContained=true
          -p:IncludeAllContentForSelfExtract=true
        shell: cmd

      - name: Find all EXE
        run: dir /s /b PowerSwitcher.TrayApp\bin\Release\*.exe
        shell: cmd

      - name: Archive EXE
        run: powershell Compress-Archive -Path PowerSwitcher.TrayApp\bin\Release\**\PowerSwitcher.TrayApp.exe -DestinationPath PowerSwitcher.zip
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: PowerSwitcher
          path: PowerSwitcher.zip
