name: Build PowerSwitcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish PowerSwitcher
        run: >
          dotnet publish PowerSwitcher\PowerSwitcher.csproj
          -c Release -r win-x64
          -o output
          /p:PublishSingleFile=true
          /p:SelfContained=false
        shell: cmd

      - name: List output folder
        run: dir /s output
        shell: cmd

      - name: Compress PowerSwitcher.exe to ZIP
        run: powershell Compress-Archive -Path output\PowerSwitcher.exe -DestinationPath output\PowerSwitcher.zip

      - uses: actions/upload-artifact@v4
        with:
          name: PowerSwitcher
          path: output/PowerSwitcher.zip
