name: Build PowerSwitcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: |
        dotnet publish PowerSwitcher.TrayApp/PowerSwitcher.TrayApp.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PowerSwitcher
        path: PowerSwitcher.TrayApp/bin/Release/net8.0/win-x64/publish/
