name: Build PowerSwitcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Show current directory and files before publish
        shell: cmd
        run: |
          cd
          dir

      - name: Publish PowerSwitcher
        shell: cmd
        run: |
          cd PowerSwitcher
          dotnet publish PowerSwitcher.csproj -c Release -r win-x64 -o "%GITHUB_WORKSPACE%\output" /p:PublishSingleFile=true /p:SelfContained=false

      - name: Show files in publish folder
        shell: cmd
        run: dir "%GITHUB_WORKSPACE%\output"

      - uses: actions/upload-artifact@v4
        with:
          name: PowerSwitcher
          path: output\PowerSwitcher.exe
